packages:
  - packages/*
  - examples/*
  - e2e
  - fixtures/e2e-apps/electron-builder
  - fixtures/e2e-apps/electron-forge
  - fixtures/e2e-apps/electron-no-binary
  - fixtures/e2e-apps/tauri
  - fixtures/package-tests/electron-builder-app-cjs
  - fixtures/package-tests/electron-builder-app-esm
  - fixtures/package-tests/electron-forge-app-cjs
  - fixtures/package-tests/electron-forge-app-esm
  - fixtures/package-tests/electron-script-app-cjs
  - fixtures/package-tests/electron-script-app-esm
  - fixtures/package-tests/tauri-app

catalogs:
  default:
    electron: 38.3.0
    webdriverio: ^9.20.0
    '@wdio/cli': ^9.20.0
    '@wdio/globals': ^9.17.0
    '@wdio/local-runner': ^9.20.0
    '@wdio/mocha-framework': ^9.20.0
    '@wdio/types': ^9.20.0
    '@wdio/logger': ^9.18.0
    '@wdio/xvfb': ^9.20.0
    '@wdio/spec-reporter': ^9.20.0
  next:
    electron-nightly: 40.0.0-nightly.20251010
    webdriverio: latest
    '@wdio/cli': latest
    '@wdio/globals': latest
    '@wdio/local-runner': latest
    '@wdio/mocha-framework': latest
    '@wdio/types': latest
    '@wdio/logger': latest
    '@wdio/xvfb': latest
    '@wdio/spec-reporter': latest
  minimum:
    electron: 28.3.3
    webdriverio: ^8.43.0
    '@wdio/cli': ^8.43.0
    '@wdio/globals': ^8.43.0
    '@wdio/local-runner': ^8.43.0
    '@wdio/mocha-framework': ^8.41.0
    '@wdio/types': ^8.41.0
    '@wdio/logger': ^8.41.0
    '@wdio/xvfb': ^9.19.1
    '@wdio/spec-reporter': ^9.19.1
