packages:
  - packages/*
  - examples/*
  - e2e
  - fixtures/electron-apps/builder-cjs
  - fixtures/electron-apps/builder-esm
  - fixtures/electron-apps/forge-cjs
  - fixtures/electron-apps/forge-esm
  - fixtures/electron-apps/no-binary-cjs
  - fixtures/electron-apps/no-binary-esm
  - fixtures/tauri-apps/basic
  - fixtures/package-tests/builder-app
  - fixtures/package-tests/forge-app
  - fixtures/package-tests/script-app

catalogs:
  default:
    electron: 38.5.0
    webdriverio: ^9.20.0
    '@wdio/cli': ^9.20.0
    '@wdio/globals': ^9.17.0
    '@wdio/local-runner': ^9.20.0
    '@wdio/mocha-framework': ^9.20.0
    '@wdio/types': ^9.20.0
    '@wdio/logger': ^9.18.0
    '@wdio/xvfb': ^9.20.0
  next:
    electron-nightly: 40.0.0-nightly.20251028
    webdriverio: latest
    '@wdio/cli': latest
    '@wdio/globals': latest
    '@wdio/local-runner': latest
    '@wdio/mocha-framework': latest
    '@wdio/types': latest
    '@wdio/logger': latest
    '@wdio/xvfb': latest
  minimum:
    electron: 28.3.3
    webdriverio: ^8.43.0
    '@wdio/cli': ^8.43.0
    '@wdio/globals': ^8.43.0
    '@wdio/local-runner': ^8.43.0
    '@wdio/mocha-framework': ^8.41.0
    '@wdio/types': ^8.41.0
    '@wdio/logger': ^8.41.0
    '@wdio/xvfb': ^9.19.1

